#!/usr/bin/env python3
# -----------------------------------------------------------------------------------------------------------
# Copyright (c) 2025 Huawei Technologies Co., Ltd.
# CANN Open Software License Agreement Version 2.0. See LICENSE for details.
# -----------------------------------------------------------------------------------------------------------
"""
AICPU 后端「注册层」代码生成器(仿 NCCL device/generate.py)。

输入: 一个或多个 src/ops/<op>/aicpu.spec.yaml
输出(--out 目录):
  - alg_names.h           : 每个 algName 的 constexpr 字符串常量(单一真值源)
  - <op>_aicpu_reg.cc     : 每个变体一条静态 Register() 调用

设计见 docs/zh/design/aicpu_codegen_refactor.md。生成文件勿手改。
"""
import argparse
import os
import sys

try:
    import yaml
except ImportError:
    sys.stderr.write("gen_aicpu.py: PyYAML is required (pip install pyyaml)\n")
    raise

HEADER = (
    "// -------------------------------------------------------------------------\n"
    "// AUTO-GENERATED by tools/codegen/gen_aicpu.py. DO NOT EDIT.\n"
    "// Source spec(s): {specs}\n"
    "// -------------------------------------------------------------------------\n"
)


def load_specs(spec_paths):
    specs = []
    for p in spec_paths:
        with open(p, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f)
        if not data:
            continue
        data["_path"] = p
        specs.append(data)
    return specs


def gen_alg_names(specs):
    names = []
    for s in specs:
        for v in s.get("variants", []):
            names.append(v["name"])
    # 去重保序
    seen = set()
    uniq = [n for n in names if not (n in seen or seen.add(n))]
    lines = [
        "#ifndef HCCL_GENERATED_AICPU_ALG_NAMES_H",
        "#define HCCL_GENERATED_AICPU_ALG_NAMES_H",
        "",
        "namespace ops_hccl {",
        "namespace algnames {",
        "// namespace 作用域 constexpr -> 内部链接, 各 TU 私有拷贝, C++14 下 ODR 安全",
    ]
    for n in uniq:
        lines.append('constexpr char {n}[] = "{n}";'.format(n=n))
    lines += ["}  // namespace algnames", "}  // namespace ops_hccl", "", "#endif", ""]
    return "\n".join(lines)


def _exec_type(v):
    """拼出 Executor<Topo, Tmpl0, Tmpl1...> 全限定模板实参串。"""
    args = [v["topo"]] + list(v.get("templates", []))
    return "{exec}<{args}>".format(exec=v["executor"], args=", ".join(args))


def gen_reg_cc(spec):
    op = spec["op"]
    cmd = spec["cmd"]
    includes = spec.get("includes", [])
    out = [HEADER.format(specs=spec["_path"])]
    out.append('#include "coll_alg_v2_exec_registry.h"')
    out.append('#include "alg_names.h"')
    for inc in includes:
        out.append('#include "{}"'.format(inc))
    out.append("")
    out.append("namespace ops_hccl {")
    for v in spec.get("variants", []):
        name = v["name"]
        sym = "g_reg_{op}_{name}".format(op=op, name=name)
        out.append("// {name}".format(name=name))
        out.append("static HcclResult {sym} =".format(sym=sym))
        out.append("    CollAlgExecRegistryV2::Instance().Register(")
        out.append("        HcclCMDType::{cmd},".format(cmd=cmd))
        out.append("        std::string(algnames::{name}),".format(name=name))
        out.append("        DefaultExecCreatorV2<{t}>);".format(t=_exec_type(v)))
        out.append("")
    out.append("}  // namespace ops_hccl")
    out.append("")
    return "\n".join(out)


def check_selector(specs, selector_files):
    """CI 校验: 已迁入 codegen 的 algName 不应再以裸字符串字面量出现在 selector 中,
    必须改用 algnames::<name> 常量(单一真值源)。捕获回归。"""
    names = [v["name"] for s in specs for v in s.get("variants", [])]
    bad = []
    for f in selector_files:
        with open(f, "r", encoding="utf-8") as fh:
            text = fh.read()
        for n in names:
            if '"{}"'.format(n) in text:
                bad.append((f, n))
    if bad:
        for f, n in bad:
            sys.stderr.write(
                'gen_aicpu.py: CHECK FAILED: migrated algName "{n}" still a raw literal in '
                '{f}\n  -> use algnames::{n} (include alg_names.h)\n'.format(n=n, f=f))
        sys.exit(1)
    print("gen_aicpu.py: selector check OK ({} migrated names x {} selector file(s))".format(
        len(names), len(selector_files)))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True, help="output directory")
    ap.add_argument("--check-selector", action="append", default=[],
                    metavar="SELECTOR_CC",
                    help="selector .cc to verify carries no raw migrated-name literals "
                         "(repeat the flag for multiple files)")
    ap.add_argument("specs", nargs="+", help="aicpu.spec.yaml file(s)")
    args = ap.parse_args()

    os.makedirs(args.out, exist_ok=True)
    specs = load_specs(args.specs)

    with open(os.path.join(args.out, "alg_names.h"), "w", encoding="utf-8") as f:
        f.write(gen_alg_names(specs))

    for s in specs:
        fname = "{op}_aicpu_reg.cc".format(op=s["op"])
        with open(os.path.join(args.out, fname), "w", encoding="utf-8") as f:
            f.write(gen_reg_cc(s))

    print("gen_aicpu.py: generated alg_names.h + {} reg file(s) into {}".format(
        len(specs), args.out))

    if args.check_selector:
        check_selector(specs, args.check_selector)


if __name__ == "__main__":
    main()
