# -----------------------------------------------------------------------------------------------------------
# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# refactor UT 入口：各 refactor 模块按子目录组织
# -----------------------------------------------------------------------------------------------------------
add_subdirectory(executor)
add_subdirectory(template)
add_subdirectory(selector)