# -----------------------------------------------------------------------------------------------------------
# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# refactor/template unit test entry.
# -----------------------------------------------------------------------------------------------------------

add_subdirectory(primitives)
